### ISSUE TITLE
Can you guide me through this line of code

### ISSUE THREAD

**Issue by sahil2897** [ekzhang/vae-cnn-mnist#1]
outputs = decoder([encoder(inputs)[2], label_inputs]).

I printed the output of encoder(inputs). It gives the last 3 layers of encoder.  why?. Please Help. Thanks in advance.

**Comment by ekzhang** [comment]
See this line https://github.com/ekzhang/vae-cnn-mnist/blob/master/model.py#L44. The encoder outputs not only z, but also variational parameters for mean and variance.
